name: Sample CI Pipeline

on:
    push:
        branches:
            [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build app
              run : echo "build app done"
    test:
        runs-on: ubuntu-latest
        steps:
            - name: test app
              run: echo "test app done"
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy app
              run: echo "deploy app done" 

